import img1 from '$lib/imgs/IMG_20170923.jpg';
import img2 from '$lib/imgs/IMG_20171231.jpg';
import img3 from '$lib/imgs/IMG_20180523.jpg';
import img4 from '$lib/imgs/IMG_20180811.jpg';
import img5 from '$lib/imgs/IMG_20190723.jpg';
import img6 from '$lib/imgs/IMG_20190904.jpg';
import img7 from '$lib/imgs/IMG_20191003.jpg';
import img8 from '$lib/imgs/IMG_20210126.jpg';


export const cats = [
    {
        "id": 1,
        "image": img1,
        "alt": "Oranger Kater auf dem Sofa",
        "picturedCats": ["Kusja"],
        "date": new Date("2017-09-23"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 2,
        "image": img2,
        "alt": "Oranger Kater putzt schwarzes Kätzchen",
        "picturedCats": ["Kusja", "Wasja"],
        "date": new Date("2017-12-31"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 3,
        "image": img3,
        "alt": "Schwarzer und Oranger Kater auf dem Balkon",
        "picturedCats": ["Kusja", "Wasja"],
        "date": new Date("2018-05-23"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 4,
        "image": img4,
        "alt": "Schwarzer Kater liegt auf einer Decke",
        "picturedCats": ["Wasja"],
        "date": new Date("2018-08-12"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 5,
        "image": img5,
        "alt": "Schwarze-weißes Kätzchen sitzt auf einer Sessellehne",
        "picturedCats": ["Tjoma"],
        "date": new Date("2019-07-23"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 6,
        "image": img6,
        "alt": "Schwarzer Kater und schwarz-weißes Kätzchen schlafen auf einem Bürostuhl",
        "picturedCats": ["Wasja", "Tjoma"],
        "date": new Date("2019-09-04"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 7,
        "image": img7,
        "alt": "Schwarzer Kater und schwarz-weißes Kätzchen liegen auf zwei Stühlen",
        "picturedCats": ["Wasja", "Tjoma"],
        "date": new Date("2019-10-03"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    },
    {
        "id": 8,
        "image": img8,
        "alt": "Schwarzweiße Katze auf dem Regal",
        "picturedCats": ["Tjoma"],
        "date": new Date("2021-01-26"),
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc odio, convallis quis laoreet quis, fringilla nec nulla. Pellentesque eget dui id lectus posuere interdum eu id mauris. Donec non eros convallis, scelerisque odio eget, ultricies erat. Duis erat ante, eleifend sit amet hendrerit quis, pharetra in augue. Aenean in risus quis sem venenatis imperdiet eget id eros. Aenean ornare tempor viverra. Praesent lobortis massa vitae ante tempus, et ultricies lorem posuere. Aliquam semper posuere mollis. Vestibulum nec urna ultrices, rutrum ex eu, ultricies orci. Donec arcu sem, viverra sed lectus nec, mollis laoreet felis. Cras porta lorem eget tortor accumsan, porta posuere nibh porta. Fusce cursus mauris vitae tempus eleifend. Pellentesque auctor pretium faucibus. Vestibulum maximus dignissim leo ac posuere. Fusce enim est, pharetra quis neque ac, convallis consequat risus.\n" +
            "Nulla at neque hendrerit, malesuada eros sed, volutpat turpis. Quisque vestibulum felis id augue finibus aliquam. Sed ullamcorper felis a condimentum fringilla. Nullam nibh metus, tempus ac hendrerit faucibus, malesuada ut sapien. Aenean ut turpis sagittis, malesuada purus sit amet, placerat urna. Nam sit amet mauris a quam sodales hendrerit eget sed eros. Pellentesque id scelerisque mauris, in ornare dui. Sed nec nibh erat. Pellentesque nibh orci, pulvinar eget malesuada ac, interdum quis metus. Nullam blandit magna ante, id posuere risus luctus sit amet. Praesent vel venenatis metus. Vestibulum porttitor risus et tempor feugiat. Vivamus sagittis, massa quis porta faucibus, enim nunc suscipit elit, ac luctus dolor turpis a diam. Etiam quis orci bibendum, fermentum lorem eu, vestibulum nibh. Proin dignissim mauris ex, lobortis semper sapien consectetur vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. "
    }
]