name: ssr-workshop
services:
  prerender:
    image: ghcr.io/denwae/ssr-prerender
    ports:
      - "8080:80"
  client-side:
    image: ghcr.io/denwae/ssr-client-side
    ports:
      - "8081:80"
  server-side:
    image: ghcr.io/denwae/ssr-server-side
    ports:
      - "8082:3000"